[package]
name = "k8s-common"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
futures = { workspace = true }
globset = { workspace = true }
json-patch = { workspace = true }
k8s-openapi = { workspace = true }
kube = { workspace = true }
kube-lease-manager = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
sha2 = { workspace = true }
upon = "0.11"

axum = { workspace = true }
tower = { workspace = true }
aincrad-macros = { path = "../macros" }
