[package]
name = "cardinal"
version = "0.1.0"
edition = "2024"

[dependencies]
k8s-common = { path = "../k8s-common" }
clap = { workspace = true }
globset = { workspace = true }
json-patch = { workspace = true }
kube = { workspace = true }
kube-lease-manager = "0.12"
k8s-openapi = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3"
thiserror = { workspace = true }
chrono = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
base32 = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
siphasher = { workspace = true }
tokio-rustls = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
tower = { workspace = true }