[package]
name = "fluct"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8"
async-compression = { version = "0.4", features = ["tokio", "gzip"] }
axum = { workspace = true }
base32 = "0.5"
base64 = "0.22"
capnp = "0.27"
capnp-futures = "0.27"
chrono = { version = "0.4", features = ["serde"] }
clap = { workspace = true, features = ["derive"] }
crypto = { version = "0.5", features = ["cipher", "digest"] }
crypto-ops = "0.1"
dashmap = "6"
futures = "0.3"
gmp-mpfr-sys = "1.7"
hmac = { workspace = true }
k8s-openapi = { workspace = true, features = ["latest", "schemars"] }
kctf-pow = "2.1"
kube = { workspace = true, features = ["runtime", "derive"] }
kube-lease-manager = { workspace = true }
rand = { workspace = true }
rustls-pemfile = "2"
schemars = { workspace = true, features = ["chrono04"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-rustls = { version = "0.26", features = ["ring"] }
tokio-util = { version = "0.7", features = ["rt", "compat"] }
tower = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3"

[build-dependencies]
capnpc = "0.27"
