apiVersion: aincrad.noctf.dev/v1
kind: CTFTemplate
metadata:
  name: web-whoami
  namespace: challenges
spec:
  pods:
    - name: web
      replicas: 1
      allowInternet: false
      spec:
        containers:
          - name: app
            image: traefik/whoami:v1.10.1
            ports:
              - containerPort: 80
            resources:
              limits:
                cpu: "200m"
                memory: "128Mi"
              requests:
                cpu: "20m"
                memory: "32Mi"
  routes:
    - name: http
      backend:
        service: web
        port: 80
      tls:
        prefix: whoami
---
apiVersion: aincrad.noctf.dev/v1
kind: CTFInstance
metadata:
  name: team1-whoami
  namespace: challenges
spec:
  template: web-whoami
