# TLS Route
apiVersion: aincrad.noctf.dev/v1
kind: CTFRoute
metadata:
  name: test-web-route
  namespace: kubectf-challenges
spec:
  availableAt: 2010-12-31T00:00:00.000Z
  secret: testing
  tls:
    key: any-entropy
  backend: 10.244.0.15:8080
---
# TCP Route with auto-allocated port from Fluct
apiVersion: aincrad.noctf.dev/v1
kind: CTFRoute
metadata:
  name: test-pwn-auto-port
  namespace: kubectf-challenges
spec:
  backend: 10.244.0.16:1337
  port: 0 
---
# TCP Route with fixed port
apiVersion: aincrad.noctf.dev/v1
kind: CTFRoute
metadata:
  name: test-pwn-fixed-port
  namespace: kubectf-challenges
spec:
  backend: 10.244.0.17:1337
  port: 20001
