# TLS Route
apiVersion: aincrad.noctf.dev/v1
kind: CTFRoute
metadata:
  name: test-web-route
  namespace: kubectf-challenges
spec:
  availableAt: 2010-12-31T00:00:00.000Z
  secret: testing
  tls:
    key: any-entropy2
  backend: example.com:80
---
# TCP Route with auto-allocated port
apiVersion: aincrad.noctf.dev/v1
kind: CTFRoute
metadata:
  name: test-pwn-auto-port
  namespace: kubectf-challenges
spec:
  backend: example.com:80
  port: 0
---
# TCP Route with fixed port
apiVersion: aincrad.noctf.dev/v1
kind: CTFRoute
metadata:
  name: test-pwn-fixed-port
  namespace: kubectf-challenges
spec:
  backend: example.com:80
  port: 10000
